### PR TITLE
further improvements

### PR DESCRIPTION
**Pull request by xi**
Thanks for the quick response to #3! I noticed I missed some small things so here is a fixup.

### CODE REVIEW

**Comment by strarsis** [comment]
Thank you for this contribution.
From the code I can see that you added support for negative exponents, including proper tests. 👍 
@xi: Btw., I added your GitHub username to the [Credits section](https://github.com/strarsis/sass-math-pow/blob/master/README.md#credits).

**Comment by xi** [comment]
I cannot really take credit for the negative exponents, that already worked before. But thanks for adding me to the credits!

**Comment by strarsis** [comment]
@xi: I adjusted the credits a bit. When there are no further changes and you need it published to npm now, let me now.

**Comment by strarsis** [comment]
@xi: Published on npm as release `v0.1.7`. It may take a while to be listed on npm.

**Pull request merged**
