### PR TITLE
Use `divide()` function for compatibility with both Dart Sass and Node Sass

### LINKED ISSUE #5: TODO/Note: dart-sass
````
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($ms-return, $b)
````

### PR DESCRIPTION
**Pull request by polarbirke**
This fixes #5 and closes (supersedes) #6.

### CODE REVIEW

**Comment by polarbirke** [comment]
Travis will work if you update `node-sass`, I think – I run Node 17 locally and the tests were green with node-sass 7.0.1.

**Comment by strarsis** [comment]
Thanks!

@polarbirke: Yes, I have to improve the CI tests. Not only `node-sass` but also `ruby-sass`, `composer + ruby-sass` (older stuff) and `Dart sass` must be tested.

**Comment by strarsis** [comment]
@polarbirke: I added you to the credits section (if you don't mind): https://github.com/strarsis/sass-math-pow#:~:text=/%20Dart%20SASS%20fix%20and%20code%20improvements%20by%20polarbirke.

**Comment by polarbirke** [comment]
Thanks, appreciate it!

**Comment by polarbirke** [comment]
Hey @strarsis could you bump the version in package.json (I forgot to add that in this PR) and publish a new version to npm?

**Comment by strarsis** [comment]
@polarbirke: No problem! Just published release `v0.2.0` on `npm`:
https://www.npmjs.com/package/sass-math-pow

**Comment by polarbirke** [comment]
Fantastic, thanks a lot!

**Pull request merged**
