### PR TITLE
Use math.div() for divisions

### LINKED ISSUE #5: TODO/Note: dart-sass
````
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($ms-return, $b)
````

### PR DESCRIPTION
**Pull request by polarbirke**
This fixes #5.

### CODE REVIEW

**Comment by strarsis** [comment]
@polarbirke: Thank you for this contribution!

Would it be possible to add this fix without breaking the compatibility with older implementations like `libsass` or `ruby sass`?

**Comment by polarbirke** [comment]
I've seen Bootstrap use a workaround: https://github.com/twbs/rfs/pull/398 if you want to stay backwards-compatible 😄

**Comment by strarsis** [comment]
@polarbirke: If you could add a `divide` polyfill to this PR it would be great!

This wouldn't only fix the deprecation warnings and errors (when `/` division support is removed in future releases of `Dart Sass`), but also allow for older releases to still use this `pow` polyfill.

The documentation you add with this PR is very thorough and well-done by the way.

**Comment by strarsis** [comment]
@polarbirke: Merged #7. (Edit)
Could you also add a PR with your documentation about this, it isn't contained in this PR?
Thanks!

**Comment by polarbirke** [comment]
Ah, I intentionally left out the upgrading guide because now it's an "invisible" fix that doesn't change the interface or requirements for consumers.

What do you think should be documented?

**Comment by strarsis** [comment]
@polarbirke: You are right, this can be left it out.

**Comment by polarbirke** [comment]
Replaced by #7 (better solution without breaking change).

**Pull request closed without merging**
